//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public int Id { get; set; }
        public Nullable<int> MenuItemId { get; set; }
        public System.DateTime Date { get; set; }
        public int QuantityState { get; set; }
        public decimal Price { get; set; }
    
        public virtual MenuItems MenuItems { get; set; }
    }
}
