//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOrder
    {
        public int Id { get; set; }
        public System.DateTime OperationTime { get; set; }
        public string OrderNotes { get; set; }
        public int OrderStatus_Id { get; set; }
        public int Place_Id { get; set; }
        public string User_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Places Places { get; set; }
        public virtual ClientOrderDetails ClientOrderDetails { get; set; }
    }
}
