//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBAR
{
    using System;
    
    public partial class getXhiroDitoreTotalAllUser_Result1
    {
        public string UserId { get; set; }
        public Nullable<decimal> XhiroReale { get; set; }
        public Nullable<decimal> XhiroKase { get; set; }
    }
}
