//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuCategories()
        {
            this.MenuItems = new HashSet<MenuItems>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Media_Id { get; set; }
        public int Place_Id { get; set; }
        public byte[] CategoryImage { get; set; }
        public int OnlineId { get; set; }
        public bool IsItemActive { get; set; }
        public string Printer { get; set; }
    
        public virtual Places Places { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItems> MenuItems { get; set; }
    }
}
