//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItems()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.Balance = new HashSet<Balance>();
            this.Goods_Dispatch_Note_Details = new HashSet<Goods_Dispatch_Note_Details>();
            this.Goods_Received_Note_Details = new HashSet<Goods_Received_Note_Details>();
            this.PriceList = new HashSet<PriceList>();
            this.ComposedItems = new HashSet<ComposedItems>();
            this.ComposedItems1 = new HashSet<ComposedItems>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public int MenuCategory_Id { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
        public int MinimumQuantityNotify { get; set; }
        public int OnlineId { get; set; }
        public bool IsItemActive { get; set; }
        public int MenuItemTypeId { get; set; }
        public int UnitId { get; set; }
    
        public virtual MenuCategories MenuCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Balance> Balance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goods_Dispatch_Note_Details> Goods_Dispatch_Note_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goods_Received_Note_Details> Goods_Received_Note_Details { get; set; }
        public virtual LastBalance LastBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceList> PriceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComposedItems> ComposedItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComposedItems> ComposedItems1 { get; set; }
        public virtual MenuItemType MenuItemType { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
