//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSessions
    {
        public int Id { get; set; }
        public int Order_Id { get; set; }
        public string User_Id { get; set; }
        public int Table_Id { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Tables Tables { get; set; }
    }
}
