//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.OrderSessions = new HashSet<OrderSessions>();
            this.OrderForCancellation = new HashSet<OrderForCancellation>();
        }
    
        public int Id { get; set; }
        public int Table_Id { get; set; }
        public System.DateTime OperationTime { get; set; }
        public int OrderStatus_Id { get; set; }
        public string User_Id { get; set; }
        public bool FiscalCash { get; set; }
        public int POS_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSessions> OrderSessions { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Tables Tables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderForCancellation> OrderForCancellation { get; set; }
    }
}
