//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public decimal SalePrice { get; set; }
        public int MenuItem_Id { get; set; }
        public int Order_Id { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual MenuItems MenuItems { get; set; }
    }
}
