//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int Id { get; set; }
        public int Orders_No { get; set; }
        public int Sold_Items_No { get; set; }
        public decimal Orders_Total_Sum { get; set; }
        public decimal Cash_Total { get; set; }
        public decimal Tips_Total_Sum { get; set; }
        public System.DateTime Date_Time { get; set; }
        public int Place_Id { get; set; }
        public string User_Id { get; set; }
        public decimal Fiscal_Orders_Total_Sum { get; set; }
        public System.DateTime Start_Date_Time { get; set; }
        public int POS_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
